/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dormidospizza;

import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author ACER
 */
public class Administración extends javax.swing.JFrame {

    ArrayList<Pizzas> listaGT = new ArrayList<>();
    ArrayList<Pizzas> listaEP = new ArrayList<>();
    ArrayList<Pizzas> listaJ = new ArrayList<>();
    Ordenar or = new Ordenar();
    
    

    /**
     * Creates new form Administración
     */
    public Administración() {
        initComponents();
    }
    
    public ArrayList<Pizzas> getListaGT(){
        return listaGT;
    }
    
    public ArrayList<Pizzas> getListaEP(){
        return listaEP;
    }
    public ArrayList<Pizzas> getListaJ(){
        return listaJ;
    }
    
    /*----------------------MÉTODOS SUCURSAL GUATEMALA------------------------*/
    public void GuardarPizzaGT() {

        Pizzas newpizzaGT = new Pizzas();
        newpizzaGT.setNombre(txtnombre.getText());
        newpizzaGT.setPrecio/*(Integer.parseInt*/(txtprecio.getText());
        newpizzaGT.setDescripcion(txtdescripcion.getText());
        listaGT.add(newpizzaGT);

        JOptionPane.showMessageDialog(null, "Nueva Dormidos Pizza agregada a la sucursal de Guatemala");
    }

    public void VerPizzasGT() {
        String listagt[][] = new String[listaGT.size()][4];
        for (int l1 = 0; l1 <listaGT.size(); l1++) {
            listagt[l1][0] = listaGT.get(l1).getNombre();
            listagt[l1][1] = listaGT.get(l1).getPrecio();
            listagt[l1][2] = listaGT.get(l1).getDescripcion();

        }
        tabla.setModel(new javax.swing.table.DefaultTableModel(
                listagt,
                new String[]{
                    "Nombre", "Descripción", "Precio"
                }
        ));

    }

    /*----------------------MÉTODOS SUCURSAL EL PROGRESO------------------------*/
    private void GuardarPizzaEP() {
        Pizzas newpizzaEP = new Pizzas();
        newpizzaEP.setNombre(txtnombre.getText());
        newpizzaEP.setPrecio(txtprecio.getText());
        newpizzaEP.setDescripcion(txtdescripcion.getText());
        listaEP.add(newpizzaEP);
        JOptionPane.showMessageDialog(null, "Nueva Dormidos Pizza agregada a la sucursal de El Progreso");

    }

    public void VerPizzasEP() {
        String listaep[][] = new String[listaEP.size()][4];
        for (int l2 = 0; l2 < listaEP.size(); l2++) {
            listaep[l2][0] = listaEP.get(l2).getNombre();
            listaep[l2][1] = listaEP.get(l2).getPrecio();
            listaep[l2][2] = listaEP.get(l2).getDescripcion();

        }
        tabla.setModel(new javax.swing.table.DefaultTableModel(
                listaep,
                new String[]{
                    "Nombre", "Descripción", "Precio"
                }
        ));

    }

    /*----------------------MÉTODOS SUCURSAL JALAPA------------------------*/
    private void GuardarPizzaJ() {
        Pizzas newpizzaJ = new Pizzas();
        newpizzaJ.setNombre(txtnombre.getText());
        newpizzaJ.setPrecio(txtprecio.getText());
        newpizzaJ.setDescripcion(txtdescripcion.getText());
        listaJ.add(newpizzaJ);
        JOptionPane.showMessageDialog(null, "Nueva Dormidos Pizza agregada a la sucursal de Jalapa");
    }

    public void VerPizzasJ() {
        String listaj[][] = new String[listaJ.size()][4];
        for (int l3 = 0; l3 < listaJ.size(); l3++) {
            listaj[l3][0] = listaJ.get(l3).getNombre();
            listaj[l3][1] = listaJ.get(l3).getPrecio();
            listaj[l3][2] = listaJ.get(l3).getDescripcion();

        }
        tabla.setModel(new javax.swing.table.DefaultTableModel(
                listaj,
                new String[]{
                    "Nombre", "Descripción", "Precio"
                }
        ));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombrepizzalabel = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        preciolabel = new javax.swing.JLabel();
        descripcionlabel = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botoncrear = new javax.swing.JButton();
        combosc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        prueba = new javax.swing.JLabel();
        ordenaradmin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        nombrepizzalabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        nombrepizzalabel.setForeground(new java.awt.Color(0, 0, 102));
        nombrepizzalabel.setText("NOMBRE:");

        preciolabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        preciolabel.setForeground(new java.awt.Color(0, 0, 102));
        preciolabel.setText("PRECIO:");

        descripcionlabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        descripcionlabel.setForeground(new java.awt.Color(0, 0, 102));
        descripcionlabel.setText("DESCRIPCIÓN:");

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Playbill", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PIZZAS");

        botoncrear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botoncrear.setForeground(new java.awt.Color(0, 0, 102));
        botoncrear.setText("CREAR");
        botoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearActionPerformed(evt);
            }
        });

        combosc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guatemala", "El Progreso", "Jalapa" }));
        combosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboscActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("SUCURSAL:");

        txtdescripcion.setColumns(20);
        txtdescripcion.setRows(5);
        jScrollPane1.setViewportView(txtdescripcion);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripción", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        ordenaradmin.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ordenaradmin.setForeground(new java.awt.Color(0, 0, 102));
        ordenaradmin.setText("MENÚ");
        ordenaradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenaradminActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Stencil", 2, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("DORMIDOS");

        jLabel4.setFont(new java.awt.Font("Stencil", 2, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("PIZZA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descripcionlabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(preciolabel)
                                .addComponent(nombrepizzalabel)))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(combosc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(423, 423, 423)
                        .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(ordenaradmin, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(prueba)
                        .addGap(186, 186, 186))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombrepizzalabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(preciolabel))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descripcionlabel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ordenaradmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordenaradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenaradminActionPerformed
        or.setVisible(true);
        or.setListaGT(listaGT);
        or.setListaEP(listaEP);
        or.setListaJ(listaJ);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_ordenaradminActionPerformed

    private void comboscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboscActionPerformed
        // PRUEBA PARA VER FUNCIONAMIENTO

        /*String mensajeprueba= "la sucursal elegida es: ";
        mensajeprueba = mensajeprueba+combosc.getSelectedItem().toString();
        prueba.setText(mensajeprueba);*/
    }//GEN-LAST:event_comboscActionPerformed

    private void botoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearActionPerformed
        String seleccionS = (String) combosc.getSelectedItem();
        
        switch (seleccionS) {
            case "Guatemala" -> {
                GuardarPizzaGT();
                VerPizzasGT();
            }
            case "El Progreso" -> {
                GuardarPizzaEP();
                VerPizzasEP();
            }
            case "Jalapa" -> {
                GuardarPizzaJ();
                VerPizzasJ();
            }
            default -> {
            }
        }
        txtnombre.setText("");
        txtprecio.setText("");
        txtdescripcion.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_botoncrearActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administración().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncrear;
    private javax.swing.JComboBox<String> combosc;
    private javax.swing.JLabel descripcionlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombrepizzalabel;
    private javax.swing.JButton ordenaradmin;
    private javax.swing.JLabel preciolabel;
    private javax.swing.JLabel prueba;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
